//Déclaration de la tab liste de produits

export let listProduits = [ 
    { 
        id: 1, 
        designation: "Réfrigérateur", 
        brief_description: "Réfrigérateur à grande capacité", 
        description: "Réfrigérateur de 300L avec congélateur intégré, système de dégivrage automatique.", 
        prix: 800, 
        quantite_initiale: 10, 
        quantite_achetee: 0, 
        quantite_restante: 10, 
        reduction: 10, 
        montant_acquis: 0,
        image : "./images/prd1.webp",
    }, 
    { 
        id: 2, 
        designation: "Lave-linge", 
        brief_description: "Lave-linge à chargement frontal", 
        description: "Capacité de 8kg, plusieurs programmes de lavage, efficacité énergétique A+++.", 
        prix: 500, 
        quantite_initiale: 15, 
        quantite_achetee: 0, 
        quantite_restante: 15, 
        reduction: 5, 
        montant_acquis: 0,
        image : "./images/prd2.webp",
    }, 
    { 
        id: 3, 
        designation: "Micro-ondes", 
        brief_description: "Micro-ondes avec fonction grill", 
        description: "Micro-ondes de 25L, grill intégré, multiples fonctions de cuisson.", 
        prix: 200, 
        quantite_initiale: 20, 
        quantite_achetee: 0, 
        quantite_restante: 20, 
        reduction: 0, 
        montant_acquis: 0,
        image : "./images/prd3.jpg",
    }, 
    { 
        id: 4, 
        designation: "Aspirateur", 
        brief_description: "Aspirateur sans sac", 
        description: "Aspirateur sans sac, filtre HEPA, idéal pour les sols durs et les tapis.", 
        prix: 150, 
        quantite_initiale: 12, 
        quantite_achetee: 0, 
        quantite_restante: 12, 
        reduction: 5, 
        montant_acquis : 0,
        image : "./images/prd4.jpg",
    }, 
    { 
        id: 5, 
        designation: "Four électrique", 
        brief_description: "Four multifonction", 
        description: "Four électrique de 60L avec grill et chaleur tournante, 10 programmes de cuisson.", 
        prix: 350, 
        quantite_initiale: 8, 
        quantite_achetee: 0, 
        quantite_restante: 8, 
        reduction: 8, 
        montant_acquis: 0,
        image : "./images/prd5.jpg",
    }, 
    { 
        id: 6, 
        designation: "Lave-vaisselle", 
        brief_description: "Lave-vaisselle 12 couverts", 
        description: "Lave-vaisselle grande capacité, programme éco, séchage rapide.", 
        prix: 600, 
        quantite_initiale: 6, 
        quantite_achetee: 0, 
        quantite_restante: 6, 
        reduction: 10, 
        montant_acquis: 0,
        image : "./images/prd6.jpg",
    },
    { 
        id: 7, 
        designation: "Climatiseur", 
        brief_description: "Climatiseur mobile", 
        description: "Climatiseur mobile de 12 000 BTU, télécommande incluse, faible consommation d'énergie.", 
        prix: 700, 
        quantite_initiale: 10, 
        quantite_achetee: 0, 
        quantite_restante: 10, 
        reduction: 5, 
        montant_acquis: 0,
        image : "./images/prd7.webp",
    }, 
    { 
        id: 8, 
        designation: "Cafetière électrique", 
        brief_description: "Cafetière programmable", 
        description: "Cafetière avec minuterie programmable, capacité de 12 tasses, filtre permanent.", 
        prix: 100, 
        quantite_initiale: 30, 
        quantite_achetee: 0, 
        quantite_restante: 30, 
        reduction: 0, 
        montant_acquis: 0,
        image : "./images/prd8.jpg",
    }, 
    { 
        id: 9, 
        designation: "Robot de cuisine", 
        brief_description: "Robot multifonction", 
        description: "Robot de cuisine avec 10 accessoires, plusieurs vitesses et fonctions pour hacher, mixer, fouetter.", 
        prix: 250, 
        quantite_initiale: 14, 
        quantite_achetee: 0, 
        quantite_restante: 14, 
        reduction: 5, 
        montant_acquis: 0,
        image : "./images/prd10.jpeg",
    }, 
    { 
        id: 10, 
        designation: "Télévision 4K", 
        brief_description: "Téléviseur 4K UHD 55 pouces", 
        description: "Télévision 55 pouces, résolution 4K UHD, Smart TV avec accès à toutes vos plateformes de streaming préférées.", 
        prix: 1200, 
        quantite_initiale: 7, 
        quantite_achetee: 0, 
        quantite_restante: 7, 
        reduction: 10, 
        montant_acquis: 0,
        image : "./images/prd11.webp",
    } 

]